# Generated by Django 4.1.4 on 2023-06-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_followers_profile_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isVerified',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='otp',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
