# Generated by Django 4.0.6 on 2022-08-13 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0003_post_save_alter_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='save',
            new_name='savePost',
        ),
    ]
