# Generated by Django 4.0.6 on 2022-08-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='base.jpg', upload_to='posts_pics'),
        ),
    ]
