# Generated by Django 4.1.4 on 2022-12-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0005_rename_author_post_user_remove_post_constent_and_more'),
        ('users', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='likedPosts',
            field=models.ManyToManyField(blank=True, related_name='user_liked_posts', to='connect.post'),
        ),
        migrations.AddField(
            model_name='profile',
            name='savedPosts',
            field=models.ManyToManyField(blank=True, related_name='user_saved_posts', to='connect.post'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_posts',
            field=models.ManyToManyField(blank=True, related_name='user_uploaded_posts', to='connect.post'),
        ),
    ]
