# Generated by Django 4.1.4 on 2022-12-21 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_likedposts_profile_savedposts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_posts',
        ),
    ]
