# Generated by Django 4.1.4 on 2023-05-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0002_alter_message_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='last_text',
            field=models.TextField(default=''),
        ),
    ]
